# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


# load rules
# -----------------------------------------------------
include: "rules/mask_repeat.smk"
include: "rules/map_rna.smk"
include: "rules/trinity.smk"
include: "rules/pasa.smk"
include: "rules/gene_prediction.smk"
include: "rules/evm_combine.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        "results/evm/1GS-002/1GS-002.EVM.aa.fasta",
    default_target: True
