# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yml"


import pandas as pd

try:
    SAMPLES_DF = pd.read_csv("config/samples.tsv", sep="\t")
    SAMPLES = SAMPLES_DF["id"].tolist()

except FileNotFoundError:
    msg = "config/samples.tsv not found. Please ensure it exists and is correctly formatted."
    raise FileNotFoundError(msg)


# load rules
include: "rules/common.smk"
include: "rules/mask_repeat.smk"
include: "rules/map_rna.smk"
include: "rules/trinity.smk"
include: "rules/pasa.smk"
include: "rules/gene_prediction.smk"
include: "rules/evm_combine.smk"


# optional messages, log and error handling
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        expand("results/evm/{sample}/{sample}.EVM.aa.fasta", sample=SAMPLES),
    default_target: True
