container_mirror: docker.xuanyuan.me

pasa_config:
  params:
    validate_alignments_in_db.dbi:
      --MIN_PERCENT_ALIGNED: 75
      --MIN_AVG_PER_ID: 95
      --NUM_BP_PERFECT_SPLICE_BOUNDARY: 0

    subcluster_builder.dbi:
      -m: 50

evm_weights:
  PROTEIN:
    miniprot: 10
  TRANSCRIPT:
    gmap: 5
    blat: 5
    assembler: 7.5
  ABINITIO_PREDICTION:
    FGENESH: 5
    SNAP: 4
    EviAnn: 7.5
  OTHER_PREDICTION:
    transdecoder: 5

rna_seq_tissues:
  - fringe
  - leaf
  - root
  - seedling
