# ---------------------------------------------------
# PASA Pipeline Configuration
# ---------------------------------------------------
pasa_config:
  params:
    validate_alignments_in_db.dbi:
      --MIN_PERCENT_ALIGNED: 75
      --MIN_AVG_PER_ID: 95
      --NUM_BP_PERFECT_SPLICE_BOUNDARY: 0

    subcluster_builder.dbi:
      -m: 50

rna_seq_tissues:
  - fringe
  - leaf
  - root
  - seedling
